// <auto-generated />
using System;
using Assignment.Infrastructure.Ef.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment.Infrastructure.Migrations
{
    [DbContext(typeof(AssignmentContext))]
    [Migration("20260512195055_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment.Infrastructure.Ef.Entities.AssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Deadline")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GradingSystemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GradingSystemId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("Assignment.Infrastructure.Ef.Entities.GradingSystemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GradingSystemEntity");
                });

            modelBuilder.Entity("Assignment.Infrastructure.Ef.Entities.GradingSystemGradeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GradingSystemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPassingGrade")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradingSystemId", "Name")
                        .IsUnique();

                    b.HasIndex("GradingSystemId", "Order")
                        .IsUnique();

                    b.ToTable("GradingSystemGradeEntity");
                });

            modelBuilder.Entity("Assignment.Infrastructure.Ef.Entities.SubmissionAttachmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SubmissionId");

                    b.ToTable("SubmissionAttachmentEntity");
                });

            modelBuilder.Entity("Assignment.Infrastructure.Ef.Entities.SubmissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("JudgementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId", "AuthorId")
                        .IsUnique();

                    b.ToTable("SubmissionEntity");
                });

            modelBuilder.Entity("Assignment.Infrastructure.Ef.Entities.SubmissionJudgementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GradingSystemGradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JudgeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GradingSystemGradeId");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.ToTable("SubmissionJudgementEntity");
                });

            modelBuilder.Entity("Assignment.Infrastructure.Ef.Entities.AssignmentEntity", b =>
                {
                    b.HasOne("Assignment.Infrastructure.Ef.Entities.GradingSystemEntity", "GradingSystem")
                        .WithMany("Assignments")
                        .HasForeignKey("GradingSystemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GradingSystem");
                });

            modelBuilder.Entity("Assignment.Infrastructure.Ef.Entities.GradingSystemGradeEntity", b =>
                {
                    b.HasOne("Assignment.Infrastructure.Ef.Entities.GradingSystemEntity", "GradingSystem")
                        .WithMany("Grades")
                        .HasForeignKey("GradingSystemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GradingSystem");
                });

            modelBuilder.Entity("Assignment.Infrastructure.Ef.Entities.SubmissionAttachmentEntity", b =>
                {
                    b.HasOne("Assignment.Infrastructure.Ef.Entities.SubmissionEntity", "Submission")
                        .WithMany("Attachments")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Assignment.Infrastructure.Ef.Entities.SubmissionEntity", b =>
                {
                    b.HasOne("Assignment.Infrastructure.Ef.Entities.AssignmentEntity", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("Assignment.Infrastructure.Ef.Entities.SubmissionJudgementEntity", b =>
                {
                    b.HasOne("Assignment.Infrastructure.Ef.Entities.GradingSystemGradeEntity", "GradingSystemGrade")
                        .WithMany("SubmissionJudgements")
                        .HasForeignKey("GradingSystemGradeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Assignment.Infrastructure.Ef.Entities.SubmissionEntity", "Submission")
                        .WithOne("Judgement")
                        .HasForeignKey("Assignment.Infrastructure.Ef.Entities.SubmissionJudgementEntity", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradingSystemGrade");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Assignment.Infrastructure.Ef.Entities.AssignmentEntity", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Assignment.Infrastructure.Ef.Entities.GradingSystemEntity", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("Assignment.Infrastructure.Ef.Entities.GradingSystemGradeEntity", b =>
                {
                    b.Navigation("SubmissionJudgements");
                });

            modelBuilder.Entity("Assignment.Infrastructure.Ef.Entities.SubmissionEntity", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Judgement");
                });
#pragma warning restore 612, 618
        }
    }
}
